#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════════
# set-static-ip.sh — Configure static IP on a fresh Debian 12 VM
# ═══════════════════════════════════════════════════════════════════════════════
# Run this before deploy.sh when the VM only has a DHCP address.
# Edit the CONFIG section below, then: chmod +x set-static-ip.sh && ./set-static-ip.sh
# ═══════════════════════════════════════════════════════════════════════════════

set -euo pipefail

# ── CONFIG ────────────────────────────────────────────────────────────────────
TARGET_IP="<GATEWAY_IP>"
TARGET_CIDR="24"
TARGET_GW="<ROUTER_IP>"    # your LAN router/default gateway
TARGET_DNS1="<ROUTER_IP>"  # primary DNS (usually the router)
TARGET_DNS2="8.8.8.8"        # fallback
# ─────────────────────────────────────────────────────────────────────────────

[[ $EUID -ne 0 ]] && { echo "Run as root."; exit 1; }

# Detect primary interface (the one with the default route)
IFACE=$(ip route show default 2>/dev/null | awk '/default/ {print $5}' | head -1)
if [[ -z "$IFACE" ]]; then
    # Fallback: first ethernet interface
    IFACE=$(ip -o link show | awk -F': ' '/^[0-9]+: e/{print $2}' | head -1)
fi
[[ -z "$IFACE" ]] && { echo "ERROR: Cannot detect network interface. Check 'ip link'."; exit 1; }

echo "Interface : $IFACE"
echo "Current   : $(ip addr show "$IFACE" | awk '/inet /{print $2}' | head -1)"
echo "Target    : ${TARGET_IP}/${TARGET_CIDR} via ${TARGET_GW}"
echo ""

NETCFG="/etc/network/interfaces"
[[ ! -f "$NETCFG" ]] && { echo "ERROR: $NETCFG not found. Is this a Debian system using ifupdown?"; exit 1; }

# Backup
cp "$NETCFG" "${NETCFG}.bak-$(date +%Y%m%d-%H%M%S)"

cat > "$NETCFG" <<EOF
# Generated by set-static-ip.sh on $(date -Iseconds)
source /etc/network/interfaces.d/*

auto lo
iface lo inet loopback

auto ${IFACE}
iface ${IFACE} inet static
    address ${TARGET_IP}/${TARGET_CIDR}
    gateway ${TARGET_GW}
    dns-nameservers ${TARGET_DNS1} ${TARGET_DNS2}
EOF

# Write resolv.conf directly (resolvconf may not be installed yet)
cat > /etc/resolv.conf <<EOF
nameserver ${TARGET_DNS1}
nameserver ${TARGET_DNS2}
EOF

echo "Written: $NETCFG"
echo "Applying — connection will drop and reconnect on new IP..."
echo ""

ifdown "$IFACE" 2>/dev/null || true
ifup "$IFACE"

echo ""
echo "Done. Verify:"
ip addr show "$IFACE"
echo ""
echo "Reconnect: ssh root@${TARGET_IP}"
