#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════════
# set-static-ip.sh — Configure static IP on a fresh Debian 12 VM
# ═══════════════════════════════════════════════════════════════════════════════
# Run this BEFORE deploy.sh when the VM only has a DHCP address.
#
# CRITICAL: Switching from DHCP to static without rebooting can leave a
# stale dhclient running. That stale client will eventually enter a renewal
# death-spiral and silently kill all inbound connections (nginx stays up but
# becomes unreachable). This script removes the DHCP client packages and
# forces a clean interface state.
#
# Edit the CONFIG section below, then: chmod +x set-static-ip.sh && ./set-static-ip.sh
# ═══════════════════════════════════════════════════════════════════════════════

set -euo pipefail

# ── CONFIG ────────────────────────────────────────────────────────────────────
TARGET_IP="<GATEWAY_IP>"
TARGET_CIDR="24"
TARGET_GW="<ROUTER_IP>"    # your LAN router/default gateway
TARGET_DNS1="<ROUTER_IP>"  # primary DNS (usually the router)
TARGET_DNS2="8.8.8.8"        # fallback
# ─────────────────────────────────────────────────────────────────────────────

[[ $EUID -ne 0 ]] && { echo "Run as root."; exit 1; }

# ── H7: refuse to run unedited / with invalid values ──────────────────────────
# Run with the <placeholders> still in place, this script purges the DHCP client
# and writes a bogus address into /etc/network/interfaces — leaving the box
# unreachable with no DHCP to fall back on. Validate the CONFIG before any of that.
_valid_ip() { [[ "$1" =~ ^(25[0-5]|2[0-4][0-9]|1?[0-9]?[0-9])(\.(25[0-5]|2[0-4][0-9]|1?[0-9]?[0-9])){3}$ ]]; }
for _v in "$TARGET_IP" "$TARGET_GW" "$TARGET_DNS1" "$TARGET_DNS2"; do
    case "$_v" in
        *"<"*|*">"*) echo "ERROR: edit the CONFIG section first — '$_v' is still a <placeholder>."; exit 1 ;;
    esac
    _valid_ip "$_v" || { echo "ERROR: '$_v' is not a valid IPv4 address — fix the CONFIG section."; exit 1; }
done
{ [[ "$TARGET_CIDR" =~ ^[0-9]+$ ]] && [ "$TARGET_CIDR" -ge 1 ] && [ "$TARGET_CIDR" -le 32 ]; } \
    || { echo "ERROR: TARGET_CIDR='$TARGET_CIDR' invalid (expect 1-32)."; exit 1; }

# Detect primary interface (the one with the default route)
IFACE=$(ip route show default 2>/dev/null | awk '/default/ {print $5}' | head -1)
if [[ -z "$IFACE" ]]; then
    # Fallback: first ethernet interface
    IFACE=$(ip -o link show | awk -F': ' '/^[0-9]+: e/{print $2}' | head -1)
fi
[[ -z "$IFACE" ]] && { echo "ERROR: Cannot detect network interface. Check 'ip link'."; exit 1; }

echo "Interface : $IFACE"
echo "Current   : $(ip addr show "$IFACE" | awk '/inet /{print $2}' | head -1)"
echo "Target    : ${TARGET_IP}/${TARGET_CIDR} via ${TARGET_GW}"
echo ""

NETCFG="/etc/network/interfaces"
[[ ! -f "$NETCFG" ]] && { echo "ERROR: $NETCFG not found. Is this a Debian system using ifupdown?"; exit 1; }

# ── Step 1: Nuke any running dhclient BEFORE touching config ──────────────────
# If we write the static config first and dhclient is still running, it can
# survive ifdown and cause the silent-death bug documented above.
echo "[1/5] Stopping any running DHCP client..."
if pgrep -x dhclient > /dev/null 2>&1; then
    echo "      Found dhclient running — killing it hard."
    pkill -x dhclient || true
    sleep 1
    # Double-tap
    pgrep -x dhclient > /dev/null 2>&1 && pkill -9 -x dhclient || true
fi

# ── Step 2: Remove DHCP client packages (static IP does not need them) ────────
echo "[2/5] Removing DHCP client packages (isc-dhcp-client, isc-dhcp-common)..."
apt-get remove --purge -y isc-dhcp-client isc-dhcp-common 2>/dev/null || {
    echo "      WARNING: Could not remove isc-dhcp-client (may not be installed)."
}

# ── Step 3: Write static config ───────────────────────────────────────────────
echo "[3/5] Writing static network config..."
cp "$NETCFG" "${NETCFG}.bak-$(date +%Y%m%d-%H%M%S)"

cat > "$NETCFG" <<EOF
# Generated by set-static-ip.sh on $(date -Iseconds)
# NOTE: DHCP client packages have been removed. This interface is STATIC only.
# If you ever need DHCP again, install isc-dhcp-client first.
source /etc/network/interfaces.d/*

auto lo
iface lo inet loopback

auto ${IFACE}
iface ${IFACE} inet static
    address ${TARGET_IP}/${TARGET_CIDR}
    gateway ${TARGET_GW}
    dns-nameservers ${TARGET_DNS1} ${TARGET_DNS2}
EOF

# Write resolv.conf directly (resolvconf may not be installed yet)
cat > /etc/resolv.conf <<EOF
nameserver ${TARGET_DNS1}
nameserver ${TARGET_DNS2}
EOF

echo "      Written: $NETCFG"

# ── Step 4: Bring interface down/up cleanly ───────────────────────────────────
echo "[4/5] Applying config — connection will drop briefly..."
# H7: run the down/up DETACHED (setsid + nohup) so it survives this SSH session
# dying the instant ifdown drops the address. Run inline, the script gets SIGHUP
# when the connection drops and ifup never executes — locking the box out.
nohup setsid bash -c "ifdown '$IFACE' 2>/dev/null; sleep 1; ifup '$IFACE'" \
    >>/var/log/set-static-ip.log 2>&1 &
echo "      Detached ifdown/ifup (pid $!) → /var/log/set-static-ip.log; waiting 8s to settle..."
sleep 8

# ── Step 5: Verify dhclient is truly gone ─────────────────────────────────────
echo "[5/5] Verifying clean state..."
if pgrep -x dhclient > /dev/null 2>&1; then
    echo ""
    echo "═══════════════════════════════════════════════════════════════════════════════"
    echo "  ⚠️  WARNING: dhclient is STILL RUNNING after cleanup."
    echo ""
    echo "  This is the exact condition that causes the silent network-death bug."
    echo "  You MUST reboot now to guarantee a clean state."
    echo "═══════════════════════════════════════════════════════════════════════════════"
    echo ""
    echo "  Run:  reboot"
    echo ""
    exit 1
fi

echo ""
echo "Done. Interface state is clean (no dhclient)."
ip addr show "$IFACE"
echo ""
echo "Reconnect: ssh root@${TARGET_IP}"
echo ""
echo "Optional: run 'reboot' now if you want 100 % certainty, but it should not"
echo "          be necessary since dhclient was killed before ifup."
